apiVersion: v1
kind: Service
metadata:
  name: wikimedia-service
spec:
  type: NodePort
  selector:
    app: wikimedia
    type: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
