apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-volume-claim
spec:
  storageClassName: {{ .Values.mysql.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
