apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: {{ .Values.mysql.rootPassword | b64enc }}
  db-user: {{ .Values.mysql.user | b64enc }}
  db-password: {{ .Values.mysql.password | b64enc }}
