- name: Add Kubernetes GPG key
  shell: curl -s {{ k8s_apt_repo_key_url }} | sudo apt-key add -
  register: apt_update_result

- name: Add Kubernetes repository
  shell: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee {{ k8s_apt_repo_list_file_path }}

- name: Install kubelet, kubeadm, and kubectl
  apt:
    name: "{{ k8s_package_list }}"
    state: present
    update_cache: yes

- name: Add Helm GPG key
  shell: curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
  changed_when: false
  
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
  changed_when: false
  
- name: Add Helm repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
  changed_when: false
  
- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: false
  
- name: Install Helm
  apt:
    name: helm
    state: present
    
- name: Hold Kubernetes packages at current version
  shell: sudo apt-mark hold kubelet kubeadm kubectl
